export const categoriesOptions = [
  {
    label: 'Company Insights',
    value: 'companyInsights',
    subItems: [
      { name: 'revenue', value: 'Revenue', categoryId: 'companyInsights' },
      { name: 'founding_year', value: 'Founding Year', categoryId: 'companyInsights' },
      { name: 'funding_rounds', value: 'Funding Rounds', categoryId: 'companyInsights' },
      { name: 'employee_count', value: 'Employee Count', categoryId: 'companyInsights' },
    ],
  },
  {
    label: 'Contact Information',
    value: 'contactInformation',
    subItems: [
      { name: 'customer_service', value: 'Customer Service', categoryId: 'contactInformation' },
      { name: 'design', value: 'Design', categoryId: 'contactInformation' },
      { name: 'education', value: 'Education', categoryId: 'contactInformation' },
      { name: 'engineering', value: 'Engineering', categoryId: 'contactInformation' },
      { name: 'finance', value: 'Finance', categoryId: 'contactInformation' },
      { name: 'health', value: 'Health', categoryId: 'contactInformation' },
      { name: 'human_resources', value: 'Human Resources', categoryId: 'contactInformation' },
      { name: 'legal', value: 'Legal', categoryId: 'contactInformation' },
      { name: 'marketing', value: 'Marketing', categoryId: 'contactInformation' },
      { name: 'media', value: 'Media', categoryId: 'contactInformation' },
      { name: 'operations', value: 'Operations', categoryId: 'contactInformation' },
      { name: 'public_relations', value: 'Public Relations', categoryId: 'contactInformation' },
      { name: 'real_estate', value: 'Real Estate', categoryId: 'contactInformation' },
      { name: 'sales', value: 'Sales', categoryId: 'contactInformation' },
      { name: 'trades', value: 'Trades', categoryId: 'contactInformation' },
    ],
  },
]

export const categoriesSubList = [
  { name: 'customer_service', value: 'Customer Service', categoryId: 'contactInformation' },
  { name: 'design', value: 'Design', categoryId: 'contactInformation' },
  { name: 'education', value: 'Education', categoryId: 'contactInformation' },
  { name: 'engineering', value: 'Engineering', categoryId: 'contactInformation' },
  { name: 'finance', value: 'Finance', categoryId: 'contactInformation' },
  { name: 'health', value: 'Health', categoryId: 'contactInformation' },
  { name: 'human_resources', value: 'Human Resources', categoryId: 'contactInformation' },
  { name: 'legal', value: 'Legal', categoryId: 'contactInformation' },
  { name: 'marketing', value: 'Marketing', categoryId: 'contactInformation' },
  { name: 'media', value: 'Media', categoryId: 'contactInformation' },
  { name: 'operations', value: 'Operations', categoryId: 'contactInformation' },
  { name: 'public_relations', value: 'Public Relations', categoryId: 'contactInformation' },
  { name: 'real_estate', value: 'Real Estate', categoryId: 'contactInformation' },
  { name: 'sales', value: 'Sales', categoryId: 'contactInformation' },
  { name: 'trades', value: 'Trades', categoryId: 'contactInformation' },
  { name: 'revenue', value: 'Revenue', categoryId: 'companyInsights' },
  { name: 'founding_year', value: 'Founding Year', categoryId: 'companyInsights' },
  { name: 'funding_rounds', value: 'Funding Rounds', categoryId: 'companyInsights' },
  { name: 'employee_count', value: 'Employee Count', categoryId: 'companyInsights' },
]
